"""Term-function enumeration and algebra helpers on finite models."""

from __future__ import annotations

from fopy.finite.models import Model
from fopy.finite.open_formulas import OpSym, Term, Variable
from fopy.finite.relops import Operation


def term_functions(model: Model, max_depth: int) -> dict[int, set[tuple[int, ...]]]:
    """Enumerate term functions up to a given term depth.

    For each arity ``k`` in ``{0, 1, 2, 3}``, collects encodings of term
    functions as output tuples on all ``k``-tuples from :attr:`~Model.universe`
    (in sorted product order).

    Args:
        model: Structure providing operations and universe.
        max_depth: Maximum term grade to enumerate.

    Returns:
        Map from arity to sets of encoded term-function tables.
    """
    from itertools import product

    result: dict[int, set[tuple[int, ...]]] = {}
    universe = model.universe
    for arity in range(4):
        terms: list[Term] = [Term.from_variable(Variable.from_index(i)) for i in range(arity)]
        ops_by_arity: dict[int, list[Operation]] = {}
        for op in model.operations.values():
            ops_by_arity.setdefault(op.arity, []).append(op)
        for depth in range(max_depth + 1):
            for t in terms:
                if t.grade() != depth:
                    continue
                rows: list[int] = []
                for args in product(universe, repeat=arity):
                    vector = {Variable.from_index(i): args[i] for i in range(arity)}
                    try:
                        rows.append(t.evaluate(model.operations, vector))
                    except (KeyError, ValueError):
                        rows.append(-1)
                result.setdefault(arity, set()).add(tuple(rows))
            if depth == max_depth:
                break
            new_terms: list[Term] = []
            for ar, ops in sorted(ops_by_arity.items()):
                for op in ops:
                    if ar == 0:
                        new_terms.append(Term.op_term(OpSym.new(op.sym, 0), []))
                    else:
                        pool = list(terms)
                        for combo in _combos(pool, ar):
                            new_terms.append(Term.op_term(OpSym.new(op.sym, ar), list(combo)))
            terms.extend(new_terms)
    return result


def subalgebra_generated_by(model: Model, generators: list[int]) -> set[int]:
    """Return the subuniverse generated by *generators* under all operations.

    Args:
        model: Structure whose operations are applied iteratively.
        generators: Seed elements (intersected with the universe).

    Returns:
        Smallest subuniverse containing the generators and closed under
        all operations of *model*.
    """
    sub = set(generators) & set(model.universe)
    changed = True
    while changed:
        changed = False
        for op in model.operations.values():
            if op.arity == 0:
                val = op.call(())
                if val is not None and val not in sub:
                    sub.add(val)
                    changed = True
                continue
            for args in _all_arg_tuples(sub, op.arity):
                val = op.call(args)
                if val is not None and val not in sub:
                    sub.add(val)
                    changed = True
    return sub


def _combos(terms: list[Term], arity: int) -> list[tuple[Term, ...]]:
    if arity == 0:
        return [()]
    result: list[tuple[Term, ...]] = [()]
    for _ in range(arity):
        result = [r + (t,) for r in result for t in terms]
    return result


def _all_arg_tuples(sub: set[int], arity: int) -> list[tuple[int, ...]]:
    elems = sorted(sub)
    result: list[tuple[int, ...]] = [()]
    for _ in range(arity):
        result = [r + (e,) for r in result for e in elems]
    return result
