"""Finite universal algebra: subalgebras, congruences, homomorphisms."""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product

from fopy.finite.algebra import subalgebra_generated_by
from fopy.finite.models import Model
from fopy.finite.relops import Operation as Operation
from fopy.universal.lattice_views import CongruenceLattice, SubalgebraLattice


@dataclass(frozen=True)
class Congruence:
    """Equivalence relation on a finite universe, stored as a partition.

    Attributes:
        classes: Disjoint blocks covering the universe; each block is a frozenset
            of universe indices.
    """

    classes: tuple[frozenset[int], ...]

    def as_relation(self, universe: list[int]) -> set[tuple[int, int]]:
        """Expand the partition into the full binary relation on *universe*.

        Args:
            universe: Universe elements (used for validation context only).

        Returns:
            Set of ordered pairs ``(a, b)`` equivalent under this congruence.
        """
        pairs: set[tuple[int, int]] = set()
        for cls in self.classes:
            for a in cls:
                for b in cls:
                    pairs.add((a, b))
        return pairs


def subalgebra(model: Model, generators: list[int]) -> set[int]:
    """Return the subuniverse generated by *generators*.

    Args:
        model: Finite algebra.
        generators: Seed universe elements.

    Returns:
        Set of universe indices in the generated subalgebra.
    """
    return subalgebra_generated_by(model, generators)


def is_subalgebra(model: Model, sub: set[int]) -> bool:
    """Check whether *sub* is closed under all operations of *model*.

    Args:
        model: Finite algebra.
        sub: Candidate subuniverse.

    Returns:
        ``True`` when every defined operation maps tuples in *sub* back into *sub*.
    """
    for op in model.operations.values():
        if op.arity == 0:
            val = op.call(())
            if val is not None and val not in sub:
                return False
            continue
        for args in product(sub, repeat=op.arity):
            val = op.call(args)
            if val is not None and val not in sub:
                return False
    return True


def homomorphisms(model: Model, target: Model) -> list[dict[int, int]]:
    """Enumerate homomorphisms from *model* to *target*.

    Intended for small universes only (both sizes at most 6); returns an
    empty list when either universe is larger.

    Args:
        model: Source algebra.
        target: Target algebra (symbols and arities must align with *model*).

    Returns:
        List of universe maps ``source_index -> target_index`` that preserve
        all operations.
    """
    if len(model.universe) > 6 or len(target.universe) > 6:
        return []
    maps: list[dict[int, int]] = []

    def compatible(m: dict[int, int]) -> bool:
        """Return whether partial map *m* respects all operation tables."""

        for op_name, op in model.operations.items():
            top = target.operations.get(op_name)
            if top is None:
                return False
            if op.arity == 0:
                s = op.call(())
                t = top.call(())
                if s is None or t is None or m.get(s) != t:
                    return False
                continue
            for args in product(model.universe, repeat=op.arity):
                s = op.call(args)
                if s is None:
                    return False
                t_args = tuple(m[a] for a in args)
                t = top.call(t_args)
                if t is None or m.get(s) != t:
                    return False
        return True

    def extend(m: dict[int, int], idx: int) -> None:
        """Backtrack-assign ``model.universe[idx]`` and recurse."""

        if idx == len(model.universe):
            if compatible(m):
                maps.append(dict(m))
            return
        a = model.universe[idx]
        for b in target.universe:
            m[a] = b
            extend(m, idx + 1)

    extend({}, 0)
    return maps


def congruence_lattice(model: Model) -> CongruenceLattice:
    """List all congruences on *model*.

    A congruence is an equivalence relation preserved by every operation.
    Exponential in universe size; for ``|U| > 5`` only the trivial congruence
    is returned.

    Args:
        model: Finite algebra.

    Returns:
        :class:`~fopy.universal.lattice_views.CongruenceLattice` of all
        congruences (supports :meth:`~fopy.universal.lattice_views.CongruenceLattice.draw`).
    """
    from fopy.universal.lattice_views import CongruenceLattice

    n = len(model.universe)
    if n > 5:
        items = [Congruence(classes=(frozenset(model.universe),))]
        return CongruenceLattice(model, items)
    universe = model.universe
    partitions = _all_partitions(universe)
    result: list[Congruence] = []
    for parts in partitions:
        if _is_congruence(model, parts):
            result.append(Congruence(classes=tuple(frozenset(p) for p in parts)))
    return CongruenceLattice(model, result)


def _is_congruence(model: Model, partition: list[set[int]]) -> bool:
    index: dict[int, int] = {}
    for i, block in enumerate(partition):
        for a in block:
            index[a] = i

    def equiv(a: int, b: int) -> bool:
        """Return whether *a* and *b* lie in the same block of *partition*."""

        return index[a] == index[b]

    for op in model.operations.values():
        if op.arity == 0:
            continue
        for args1 in product(model.universe, repeat=op.arity):
            for args2 in product(model.universe, repeat=op.arity):
                if all(equiv(a, b) for a, b in zip(args1, args2, strict=True)):
                    r1 = op.call(args1)
                    r2 = op.call(args2)
                    if r1 is None or r2 is None or not equiv(r1, r2):
                        return False
    return True


def _all_partitions(items: list[int]) -> list[list[set[int]]]:
    if not items:
        return [[]]
    first, *rest = items
    sub = _all_partitions(rest)
    result: list[list[set[int]]] = []
    for part in sub:
        result.append([{first}, *part])
        for i, block in enumerate(part):
            new_part = [set(block) for block in part]
            new_part[i].add(first)
            result.append(new_part)
    return result


def is_lattice(model: Model, join: str, meet: str) -> bool:
    """Check whether *join* and *meet* form a lattice on *model*.

    Verifies idempotence, commutativity, and absorption for the named
    binary operations.

    Args:
        model: Finite algebra.
        join: Operation symbol for join (binary).
        meet: Operation symbol for meet (binary).

    Returns:
        ``True`` when the laws hold on the full universe.
    """
    u = model.universe
    join_op = model.operations.get(join)
    meet_op = model.operations.get(meet)
    if join_op is None or meet_op is None or join_op.arity != 2 or meet_op.arity != 2:
        return False
    for x in u:
        for y in u:
            if join_op.call((x, x)) != x or meet_op.call((x, x)) != x:
                return False
            if join_op.call((x, y)) != join_op.call((y, x)):
                return False
            if meet_op.call((x, y)) != meet_op.call((y, x)):
                return False
            jxy = join_op.call((x, y))
            mxy = meet_op.call((x, y))
            if jxy is None or mxy is None:
                return False
            if join_op.call((x, mxy)) != x or meet_op.call((x, jxy)) != x:
                return False
    return True


def is_distributive_lattice(model: Model, join: str, meet: str) -> bool:
    """Check whether *join* and *meet* form a distributive lattice.

    Args:
        model: Finite algebra.
        join: Operation symbol for join (binary).
        meet: Operation symbol for meet (binary).

    Returns:
        ``True`` when lattice laws and distributivity hold on the universe.
    """
    if not is_lattice(model, join, meet):
        return False
    join_op = model.operations[join]
    meet_op = model.operations[meet]
    u = model.universe
    for x in u:
        for y in u:
            for z in u:
                myz = meet_op.call((y, z))
                jxy = join_op.call((x, y))
                jxz = join_op.call((x, z))
                if myz is None or jxy is None or jxz is None:
                    return False
                if join_op.call((x, myz)) != meet_op.call((jxy, jxz)):
                    return False
    return True


def is_boolean_algebra(model: Model, join: str, meet: str, neg: str) -> bool:
    """Check whether *join*, *meet*, and *neg* form a Boolean algebra.

    Requires a distributive lattice with complements mapping each element to
    bounds ``min(universe)`` and ``max(universe)``.

    Args:
        model: Finite algebra.
        join: Operation symbol for join (binary).
        meet: Operation symbol for meet (binary).
        neg: Operation symbol for complement (unary).

    Returns:
        ``True`` when Boolean algebra laws hold on the universe.
    """
    if not is_distributive_lattice(model, join, meet):
        return False
    neg_op = model.operations.get(neg)
    join_op = model.operations[join]
    meet_op = model.operations[meet]
    if neg_op is None or neg_op.arity != 1:
        return False
    u = model.universe
    for x in u:
        nx = neg_op.call((x,))
        if nx is None:
            return False
        top = join_op.call((x, nx))
        bot = meet_op.call((x, nx))
        if top is None or bot is None:
            return False
        if top != max(u) or bot != min(u):
            return False
    return True


def quotient(model: Model, congruence: Congruence) -> Model:
    """Build the quotient algebra ``model / congruence``.

    Universe elements are block indices ``0 .. k-1``. Operations lift from
    chosen representatives (minimum element of each block).

    Args:
        model: Source finite algebra.
        congruence: Congruence partition on ``model.universe``.

    Returns:
        Quotient model whose universe size equals the number of blocks.

    Raises:
        ValueError: If blocks do not partition the universe.
    """
    covered: set[int] = set()
    blocks: list[frozenset[int]] = []
    for block in congruence.classes:
        if not block:
            raise ValueError("Empty congruence block")
        covered |= block
        blocks.append(block)
    if covered != set(model.universe):
        raise ValueError("Congruence blocks do not cover the universe")

    rep: dict[int, int] = {}
    index: dict[int, int] = {}
    for i, block in enumerate(blocks):
        r = min(block)
        for a in block:
            index[a] = i
            rep[i] = r

    universe = list(range(len(blocks)))
    operations: dict[str, Operation] = {}
    for sym, op in model.operations.items():
        qop = Operation(sym, op.arity)
        if op.arity == 0:
            val = op.call(())
            if val is not None:
                qop.add([index[val]])
            operations[sym] = qop
            continue
        for args in product(universe, repeat=op.arity):
            concrete = tuple(rep[a] for a in args)
            val = op.call(concrete)
            if val is not None:
                qop.add(list(args) + [index[val]])
        operations[sym] = qop

    return Model(universe=universe, operations=operations)


def is_isomorphic(left: Model, right: Model) -> bool:
    """Return whether *left* and *right* are isomorphic as algebras.

    Requires equal universe sizes and matching operation symbols. Intended for
    small models (``|U| <= 6``).

    Args:
        left: First algebra.
        right: Second algebra.

    Returns:
        ``True`` when a bijective homomorphism exists.
    """
    if len(left.universe) != len(right.universe):
        return False
    if set(left.operations) != set(right.operations):
        return False
    for sym in left.operations:
        if left.operations[sym].arity != right.operations[sym].arity:
            return False
    maps = homomorphisms(left, right)
    n = len(left.universe)
    return any(len(set(m.values())) == n and len(m) == n for m in maps)


def is_embedding(model: Model, target: Model) -> bool:
    """Return whether *model* embeds into *target* (injective homomorphism).

    Args:
        model: Source algebra.
        target: Target algebra.

    Returns:
        ``True`` when an injective homomorphism ``model -> target`` exists.
    """
    maps = homomorphisms(model, target)
    return any(len(set(m.values())) == len(model.universe) for m in maps)


def subalgebra_lattice(model: Model) -> SubalgebraLattice:
    """List all subuniverses of *model* closed under its operations.

    Exponential in ``|U|``; for ``|U| > 8`` returns only the full universe and
    singletons that happen to be closed.

    Args:
        model: Finite algebra.

    Returns:
        :class:`~fopy.universal.lattice_views.SubalgebraLattice` (supports
        :meth:`~fopy.universal.lattice_views.SubalgebraLattice.draw`).
    """
    from fopy.universal.lattice_views import SubalgebraLattice

    u = model.universe
    if len(u) > 8:
        result = [set(u)]
        for a in u:
            if is_subalgebra(model, {a}):
                result.append({a})
        return SubalgebraLattice(model, result)
    all_subs: list[set[int]] = []
    for mask in range(1, 1 << len(u)):
        sub = {u[i] for i in range(len(u)) if mask & (1 << i)}
        if is_subalgebra(model, sub):
            all_subs.append(sub)
    return SubalgebraLattice(model, all_subs)


def is_subdirectly_irreducible(model: Model) -> bool:
    """Return whether *model* has no non-trivial subdirect product decomposition.

    Uses a congruence-based test: nontrivial proper congruences that are meet-
    irreducible in the congruence lattice indicate reducibility.

    Args:
        model: Finite algebra.

    Returns:
        ``True`` when the algebra appears subdirectly irreducible under this test.
    """
    latt = congruence_lattice(model)
    trivial = {frozenset(model.universe)}
    nontrivial = [c for c in latt if set(c.classes) != trivial and len(c.classes) > 1]
    if not nontrivial:
        return True
    return len(nontrivial) == 1


def is_simple(model: Model) -> bool:
    """Return whether *model* is a simple algebra (no proper nontrivial congruences).

    An algebra is simple when its only congruences are the identity and the
    universal relation. Uses :func:`congruence_lattice` (bounded for large
    universes).

    Args:
        model: Finite algebra.

    Returns:
        ``True`` when every proper congruence is trivial.
    """
    latt = congruence_lattice(model)
    trivial_blocks = {frozenset(model.universe)}
    for cong in latt:
        blocks = set(cong.classes)
        if blocks == trivial_blocks:
            continue
        if len(cong.classes) > 1 and len(cong.classes) < len(model.universe):
            return False
    return True
