"""Term clone enumeration on small finite algebras."""

from __future__ import annotations

from fopy.finite.algebra import term_functions
from fopy.finite.models import Model


def term_clone(model: Model, *, max_depth: int = 2) -> dict[int, set[tuple[int, ...]]]:
    """Enumerate term functions of the clone generated by *model* operations.

    For universes with at most four elements, returns all term-function
    encodings up to *max_depth* (see :func:`~fopy.finite.algebra.term_functions`).
    Larger universes yield an empty map to avoid exponential blow-up.

      Args:
          model: Finite algebra whose basic operations generate the clone.
          max_depth: Maximum term grade to enumerate.

      Returns:
          Map from arity to sets of encoded term-function tables.

      Raises:
          ValueError: If ``max_depth`` is negative.
    """
    if max_depth < 0:
        raise ValueError("max_depth must be non-negative")
    if len(model.universe) > 4:
        return {}
    return term_functions(model, max_depth)
